PRAGMA foreign_keys = ON;

-- TABLA BOARD -----------------------------------
CREATE TABLE IF NOT EXISTS Board (
	BoardId INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Color TEXT,
	CreationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ModificationDate DATETIME
);

-- TABLA PANEL -----------------------------------
CREATE TABLE IF NOT EXISTS Panel (
	PanelId INTEGER PRIMARY KEY AUTOINCREMENT,
	BoardId INTEGER NOT NULL,
	Name TEXT NOT NULL,
	Color TEXT NOT NULL DEFAULT '#1A1A1A',
	"Order" INTEGER NOT NULL,
	CreationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (BoardId) REFERENCES Board (BoardId)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

-- TABLA STATUS -----------------------------------
CREATE TABLE IF NOT EXISTS Status (
	StatusId INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL
);

-- TABLA TASK -------------------------------------
CREATE TABLE IF NOT EXISTS Task (
	TaskId INTEGER PRIMARY KEY AUTOINCREMENT,
	PanelId INTEGER NOT NULL,
	Title TEXT NOT NULL,
	Description TEXT,
	Tag TEXT,
	CreationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	EndDate DATETIME,
	Priority INTEGER DEFAULT 0,
	StatusId INTEGER NOT NULL,
	Color TEXT,
	FOREIGN KEY (PanelId) REFERENCES Panel (PanelId)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY (StatusId) REFERENCES Status (StatusId)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

-- INDICES PARA OPTIMIZAR CONSULTAS ---------------
CREATE INDEX IF NOT EXISTS idx_panel_board ON Panel(BoardId);
CREATE INDEX IF NOT EXISTS idx_task_panel ON Task(PanelId);
CREATE INDEX IF NOT EXISTS idx_task_status ON Task(StatusId);
CREATE INDEX IF NOT EXISTS idx_task_title ON Task(Title);
CREATE INDEX IF NOT EXISTS idx_task_tag ON Task(Tag);
CREATE INDEX IF NOT EXISTS idx_task_priority ON Task(Priority);
CREATE INDEX IF NOT EXISTS idx_task_enddate ON Task(EndDate);

-- TABLA SAVEDFILTER ----------------------------
CREATE TABLE IF NOT EXISTS SavedFilter (
	FilterId INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	CriteriaJson TEXT NOT NULL,
	CreationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- VALORES POR DEFECTO ----------------------------
INSERT INTO Status (Name) VALUES ('Pendiente'), ('En Progreso'), ('Realizada'), ('Archivada'), ('Personalizada');